### PR TITLE
Fix up and adjust for Cardinal 22.07

### PR DESCRIPTION
**Pull request by falkTX**
Quite a few things were broken, now all fixed up and also updated to upcoming Cardinal changes.

PS: the whitespace (space vs tabs) is all over the place in your code, randomly mixing tabs and spaces. Would be great to clean that up sometime.

### CODE REVIEW

**Review by clone45 — COMMENTED** [review]
Hello!  Thanks for helping me out.  I'll try to get the whitespace issues resolved.  I'm using the Atom Editor, and maybe I have my tab settings incorrect.  I had a question.  Why do you copy the struct variables into new variables, like this?  

image

Are the structure's variables not in scope in the callback for async_dialog_filebrowser?

Thanks!
Bret

**Comment by falkTX** [comment]
> Are the structure's variables not in scope in the callback for async_dialog_filebrowser?

Those values are passed into a lambda function, so they need to have local storage.
We cannot pass regular class variables into a lamba.

**Comment by falkTX** [comment]
btw, you might to see it since your modules are there.
Just started doing a web version of cardinal too, see https://cardinal.kx.studio/

**Comment by clone45** [comment]
> btw, you might want to see it since your modules are there. Just started doing a web version of cardinal too, see https://cardinal.kx.studio/

Wow, that's amazing!  I wonder how my new front panels are going to do in that environment.  I'll contact you in the next few months.  The graphic designer should be back soon and I'll be working on the PNG based panels again soon!

**Pull request merged**
