### PR TITLE
Prevent sample from being skipped

### PR DESCRIPTION
**Pull request by RemiCollin**
I found that samples were randomly not playing. I'm not sure if this line has another use, so I just commented it out, but doing so fix the issue.

### CODE REVIEW

**Comment by clone45** [comment]
Thanks for catching this!  I'll look more deeply at your proposed fix tonight.  Cheers!

**Comment by RemiCollin** [comment]
Np ! 

In addition, I took things a little further and added a few feature 
- Stereo outputs
- "Loop switch" which restart playback at the end of the file
- Deactivate autoplay when "Trig" input is patched.

If you're interested I can PR these as well

**Comment by clone45** [comment]
Absolutely!  I'd love to take a look at those new features!

**Comment by clone45** [comment]
Remi, did your other PR contain all of the items that you wanted updated?  If so, can I delete this PR?

**Comment by RemiCollin** [comment]
Yes, should have closed it you're right ;)

**Pull request closed without merging**
